### ISSUE TITLE
!told user

### ISSUE THREAD

**Issue by ty-a** [sactage/chatbot-rb#10]
See if user received their message from the command sender

**Comment by Rinzler135** [comment]
Hi. I'm not sure how active Sactage is at the moment, so I'm not sure if/when this will be considered.

**Comment by ty-a** [comment]
Hello, don't worry I'm aware :)

**Comment by sactage** [comment]
@ty-a 
> adds issue
> doesn't code himself
shame on you

**Comment by ty-a** [comment]
@sactage I can work on it once I get back to my uni's campus.

**Comment by sactage** [comment]
@Rinzler135 what is your Wikia username

**Comment by Rinzler135** [comment]
"Xytl"

**Comment by sactage** [comment]
Added in 0b2c67a
