### ISSUE TITLE
Keeping bot working

### ISSUE THREAD

**Issue by Rinzler135** [sactage/chatbot-rb#14]
Hi @sactage,

I was just wondering what the best method of keeping the bot running constantly is? I find that every day or two I need to start it again because it has disconnected. Ideally, it would either not stop or be restarted as soon as something went wrong. Would crontab be a suitable way of achieving this, or do you have any cleverer ways of doing it?

Thanks.

**Comment by sactage** [comment]
I use [countervandalism/stillalive](https://github.com/countervandalism/stillalive).

**Comment by Rinzler135** [comment]
Thanks. That looks perfect.
