### ISSUE TITLE
!untell with underscores cannot delete message

### ISSUE THREAD

**Issue by ty-a** [sactage/chatbot-rb#15]
This is mostly just because of consistency. 

when !tell-ing a user with spaces in their name, you use underscores instead of spaces, however when !untell-ing you have to use spaces, instead of underscores otherwise it cannot find the message to delete. 

I'd suggest accepting either or if possible without making things ugly.

**Comment by sactage** [comment]
@ty-a fixed. My phone is broken so I can't pull these changes to my server until I am home, if you want to do it yourself:

`cd ~/specialchat && ./pullall && kill_bots && si --pool=chatbots`

**Comment by ty-a** [comment]
I'm currently in class, but when I am out I can do it assuming you haven't.
