### ISSUE TITLE
Wikia Chat updates causing connection issues

### ISSUE THREAD

**Issue by Rinzler135** [sactage/chatbot-rb#20]
@sactage following Wikia's update to chat at ~noon UTC today, the chatbots aren't working properly. They can be seen joining the chat room but will not respond to commands, do not log chat and disconnect almost immediately. I'm not really sure what the problem is since there aren't any error messages being logged.

**Comment by KockaAdmiralac** [comment]
Wikia updated their version of socket.io and the message format changed.

**Comment by sactage** [comment]
Fixed in #21
